# Database configuration
spring:
  datasource:
    url: jdbc:h2:mem:insurancedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Logging configuration
logging:
  level:
    root: INFO
    com.epam.masterclass: DEBUG
    org.hibernate.SQL: DEBUG
